Repository helmwave/helmwave, pull requests merged in 2021-12, with the labels that each got.

#185 bump helm v3.7.2
  go.mod
  go.sum
Labels: dependencies

#204 Add tests for pkg/log
  pkg/log/log_test.go
Labels: tests

#213 Enable linter for tests
  .golangci.yml
  cmd/helmwave/main_test.go
  pkg/action/build_test.go
  pkg/action/up_test.go
  pkg/action/yml_test.go
  pkg/helper/file_test.go
  pkg/helper/helm_test.go
  pkg/helper/http_test.go
  pkg/log/log_test.go
  pkg/parallel/parallel_test.go
  pkg/plan/export_test.go
  pkg/pubsub/pubsub_test.go
  pkg/release/config_test.go
  pkg/release/repo_test.go
  pkg/release/uniqname/validate_test.go
  pkg/release/values_test.go
  pkg/template/config_test.go
  pkg/template/extra_test.go
  pkg/template/func_test.go
Labels: tests

#243 Add simple test for helm args
  pkg/release/config_internal_test.go
Labels: size/M

#245 Add more tests
  .golangci.yml
  pkg/action/status.go
  pkg/helper/file_test.go
  pkg/helper/helm.go
  pkg/helper/helm_test.go
  pkg/helper/http.go
  pkg/helper/http_test.go
  pkg/plan/apply.go
  pkg/plan/apply_test.go
  pkg/plan/build_repos_internal_test.go
  pkg/plan/build_values_internal_test.go
  pkg/plan/destroy_test.go
  pkg/plan/export_internal_test.go
  pkg/plan/import.go
  pkg/plan/list_test.go
  pkg/plan/new_export_test.go
  pkg/plan/rollback_test.go
  pkg/plan/status.go
  pkg/plan/status_test.go
  pkg/plan/validate.go
  pkg/plan/validate_test.go
Labels: size/XL
