Repository helmwave/helmwave, pull requests merged in 2022-01, with the labels that each got.

#244 Tune goreleaser config
  .github/workflows/release.yml
  .goreleaser.yml
  .vscode/settings.json
Labels: size/M

#249 Add flag for log timestamps
  pkg/log/log.go
Labels: size/M

#247 Move progress information to other log level
  Dockerfile
  pkg/action/up.go
  pkg/helper/helm.go
Labels: size/S

#252 Update readme
  README.md
Labels: size/M

#253 fix: kubedog missing config
  pkg/helper/kubedog.go
  pkg/helper/kubedog_test.go
  pkg/plan/apply.go
  tests/kubeconfig
Labels: size/M

#255 Release 0.17.1
  cmd/helmwave/main.go
  pkg/release/config.go
Labels: size/XS

#265 Release 0.17.2
  .github/workflows/go-tests.yml
  pkg/plan/build_manifests.go
  pkg/release/upgrade.go
  pkg/template/tpl2yml.go
Labels: size/S

#268 Refactor fields
  .github/workflows/go-tests.yml
  .golangci.yml
  README.md
  pkg/plan/build_manifests.go
  pkg/release/config.go
  pkg/release/upgrade.go
  pkg/template/tpl2yml.go
  tests/01_helmwave.yml.tpl
  tests/02_helmwave.yml
Labels: size/M
