Repository helmwave/helmwave, pull requests merged in 2022-02, with the labels that each got.

#273 Enable trigger autogenerate docs workflow
  .github/workflows/goreleaser.yml
  .github/workflows/notify.yml
Labels: size/M

#274 Add note about docs in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: size/XS

#277 bump go mod
  go.mod
  go.sum
Labels: size/XS

#279 Fix dependencies versions hell
  CONTRIBUTING.md
  README.md
  go.mod
  go.sum
  pkg/log/log.go
Labels: size/S

#280 Fix docs notifications
  .github/workflows/notify.yml
Labels: size/XS

#281 Disable color helm diff
  .github/workflows/notify.yml
  pkg/log/log.go
Labels: size/S

#282 feat: disable emoji with color
  pkg/log/log.go
Labels: size/XS

#278 Release 0.18.0
  .github/workflows/container-analysis.yml
  .github/workflows/go-lint.yml
  .github/workflows/go-tests.yml
  .gitignore
  .golangci.yml
  go.mod
  go.sum
  pkg/helper/const.go
  pkg/helper/kubedog_test.go
  pkg/kubedog/annotations.go
  pkg/kubedog/manifest.go
  pkg/log/log.go
  pkg/plan/build_graph.go
  pkg/plan/diff.go
  pkg/plan/status.go
  pkg/release/config.go
  pkg/release/interface.go
  pkg/repo/config.go
  pkg/template/extra.go
  tests/01_helmwave.yml.tpl
  tests/02_helmwave.yml
  tests/kubeconfig.yaml
Labels: size/L

#283 Run notify on created release
  .github/workflows/notify.yml
Labels: size/XS
