Repository helmwave/helmwave, pull requests merged in 2022-07, with the labels that each got.

#370 Update dependencies
  go.mod
  go.sum
Labels: size/XS

#366 feat: Add dependency graph implementation
  .github/workflows/go-lint.yml
  .golangci.yml
  pkg/log/log.go
  pkg/plan/apply.go
  pkg/plan/apply_test.go
  pkg/plan/new_export_test.go
  pkg/pubsub/pubsub.go
  pkg/pubsub/pubsub_internal_test.go
  pkg/release/config.go
  pkg/release/config_export_test.go
  pkg/release/dependency.go
  pkg/release/dependency/graph.go
  pkg/release/dependency/graph_test.go
  pkg/release/dependency/node.go
  pkg/release/dependency/node_export_test.go
  pkg/release/dependency/node_test.go
  pkg/release/dependency_test.go
  pkg/release/interface.go
  pkg/release/sync.go
Labels: size/XL

#374 Chart short
  pkg/release/config.go
  tests/05_helmwave.yml
  tests/11_helmwave.yml
Labels: size/M

#372 silence kubedog klog
  go.mod
  go.sum
  pkg/kubedog/silence.go
  pkg/log/log.go
Labels: size/M

#373 feat: add contexts
  go.mod
  pkg/action/build.go
  pkg/action/diff_live.go
  pkg/action/down.go
  pkg/action/up.go
  pkg/helper/http.go
  pkg/parallel/parallel.go
  pkg/plan/apply.go
  pkg/plan/apply_test.go
  pkg/plan/build.go
  pkg/plan/build_manifests.go
  pkg/plan/destroy.go
  pkg/plan/destroy_test.go
  pkg/plan/diff.go
  pkg/plan/new_export_test.go
  pkg/release/chart_test.go
  pkg/release/get_test.go
  pkg/release/interface.go
  pkg/release/sync.go
  pkg/release/uninstall.go
  pkg/release/upgrade.go
  pkg/repo/install.go
  pkg/repo/interface.go
Labels: size/L

#379 fix: linter issues and tests
  .golangci.yml
  cmd/helmwave/completion.go
  cmd/helmwave/main.go
  pkg/helper/helm.go
  pkg/helper/http.go
  pkg/helper/in.go
  pkg/helper/yml.go
  pkg/kubedog/manifest.go
  pkg/kubedog/silence.go
  pkg/log/log.go
  pkg/log/log_internal_test.go
  pkg/log/logger.go
  pkg/plan/apply.go
  pkg/plan/build_graph.go
  pkg/plan/build_releases.go
  pkg/plan/destroy.go
  pkg/plan/diff.go
  pkg/plan/list.go
  pkg/plan/new.go
  pkg/plan/new_export_test.go
  pkg/plan/rollback.go
  pkg/registry/config.go
  pkg/registry/install.go
  pkg/registry/interface.go
  pkg/release/config.go
  pkg/release/interface.go
  pkg/release/uniqname/uniqname.go
  pkg/release/values.go
  pkg/repo/config.go
  pkg/repo/in.go
  pkg/repo/interface.go
  pkg/template/sprig.go
  pkg/template/tpl2yml.go
  pkg/template/tpl2yml_test.go
  pkg/version/version.go
Labels: size/L

#380 feat: add flag for limited parallel releases
  pkg/action/build.go
  pkg/action/build_internal_test.go
  pkg/action/diff_live.go
  pkg/action/diff_live_internal_test.go
  pkg/action/diff_plan.go
  pkg/action/diff_plan_internal_test.go
  pkg/action/down.go
  pkg/action/down_internal_test.go
  pkg/action/interface.go
  pkg/action/list.go
  pkg/action/rollback.go
  pkg/action/status.go
  pkg/action/status_internal_test.go
  pkg/action/up.go
  pkg/action/up_internal_test.go
  pkg/action/validate.go
  pkg/action/yml.go
  pkg/action/yml_internal_test.go
  pkg/plan/apply.go
Labels: size/L

#381 feat: allow to skip missing values and rendering values
  pkg/release/values.go
  pkg/release/values_export_test.go
  pkg/template/gomplate_templater.go
  pkg/template/no_templater.go
  pkg/template/sprig_templater.go
  pkg/template/tpl2yml.go
Labels: size/M
