Repository helmwave/helmwave, pull requests merged in 2022-11, with the labels that each got.

#500 Release 0.24.1
  .changes/unreleased/Fixed-20221102-220450.yaml
  .changes/unreleased/Other-20221102-221015.yaml
  go.mod
  go.sum
  pkg/plan/new.go
Labels: size/S

#516 feat: upgrade helm-diff and enable normalizing manifests
  .changes/unreleased/Dependencies-20221114-070751.yaml
  .changes/unreleased/Dependencies-20221114-070827.yaml
  .changes/unreleased/Fixed-20221114-070732.yaml
  go.mod
  go.sum
  pkg/plan/diff.go
Labels: size/M

#520 fix: deprecated chart
  pkg/release/chart.go
Labels: size/XS

#519 Release/0.24.3
  .changes/unreleased/Dependencies-20221114-070751.yaml
  .changes/unreleased/Dependencies-20221114-070827.yaml
  .changes/unreleased/Fixed-20221114-070732.yaml
  go.mod
  go.sum
  pkg/plan/diff.go
  pkg/release/chart.go
Labels: size/L
