Repository helmwave/helmwave, pull requests merged in 2022-10, with the labels that each got.

#450 Release/0.23.0
  .github/workflows/go-lint.yml
  .github/workflows/goreleaser.yml
  .github/workflows/yaml-lint.yml
  .golangci.yml
  cmd/helmwave/main.go
  go.mod
  go.sum
  pkg/action/jsonschema.go
  pkg/log/log.go
  pkg/plan/diff.go
  pkg/plan/new.go
  pkg/registry/config.go
  pkg/release/config.go
  pkg/release/values.go
  pkg/repo/config.go
Labels: size/XL

#465 Release 0.23.1
  pkg/kubedog/multitrack.go
  pkg/plan/apply.go
Labels: size/S

#471 fix: disable client-only for dry-run
  pkg/release/config.go
Labels: size/XS

#470 feat: add support for postrenderer
  .golangci.yml
  pkg/release/config.go
Labels: size/M

#474 build(deps): update all dependencies
  .github/workflows/go-tests.yml
  go.mod
  go.sum
Labels: size/XS

#481 fix: fix client ratelimiter Wait error
  .github/workflows/goreleaser.yml
  pkg/release/config.go
  pkg/release/get.go
  pkg/release/sync.go
Labels: size/S

#478 fix(ci): fix helmwave path for schema generation
  .github/workflows/goreleaser.yml
Labels: size/XS

#490 feat: use strict yaml parsing for plan
  .changes/unreleased/Breaking change!-20221022-093305.yaml
  .changes/unreleased/Other-20221022-093148.yaml
  .golangci.yml
  go.mod
  go.sum
  pkg/action/build.go
  pkg/action/build_internal_test.go
  pkg/action/diff_live.go
  pkg/action/diff_plan.go
  pkg/action/down.go
  pkg/action/list.go
  pkg/action/rollback.go
  pkg/action/status.go
  pkg/action/up.go
  pkg/action/validate.go
  pkg/action/yml_internal_test.go
  pkg/helper/yml.go
  pkg/kubedog/manifest.go
  pkg/plan/build.go
  pkg/plan/diff.go
  pkg/plan/export.go
  pkg/plan/import.go
  pkg/plan/new.go
  pkg/registry/config.go
  pkg/registry/interface.go
  pkg/release/chart_test.go
  pkg/release/config.go
  pkg/release/config_test.go
  pkg/release/get_test.go
  pkg/release/interface.go
  pkg/release/values.go
  pkg/release/values_test.go
  pkg/repo/config.go
  pkg/repo/interface.go
  pkg/template/extra.go
Labels: size/L

#483 feat: allow dependencies to be optional
  .changes/unreleased/New feature-20221021-194327.yaml
  pkg/plan/apply.go
  pkg/plan/build.go
  pkg/plan/build_graph.go
  pkg/plan/build_releases.go
  pkg/plan/new_export_test.go
  pkg/release/config.go
  pkg/release/config_test.go
  pkg/release/dependencies.go
  pkg/release/interface.go
Labels: size/L

#480 feat: download remote chart to .helmwave directory
  .changes/unreleased/Fixed-20221021-194133.yaml
  .changes/unreleased/New feature-20221021-194110.yaml
  pkg/helper/fs.go
  pkg/plan/build.go
  pkg/plan/build_charts.go
  pkg/plan/build_graph.go
  pkg/plan/build_releases.go
  pkg/plan/export.go
  pkg/plan/new.go
  pkg/plan/new_export_test.go
  pkg/plan/status.go
  pkg/plan/validate.go
  pkg/release/chart.go
  pkg/release/config.go
  pkg/release/interface.go
  pkg/release/uniqname/uniqname.go
  pkg/release/values.go
Labels: size/L

#475 feat: allow to set values delimiters
  .changes/unreleased/New feature-20221021-193553.yaml
  pkg/release/values.go
  pkg/template/gomplate_templater.go
  pkg/template/no_templater.go
  pkg/template/sprig_templater.go
  pkg/template/tpl2yml.go
Labels: size/M

#489 fix: tune jsonschema to avoid too many required fields
  .changes/unreleased/Fixed-20221021-195426.yaml
  .changes/unreleased/New feature-20221021-195548.yaml
  go.mod
  go.sum
  pkg/plan/new.go
  pkg/registry/config.go
  pkg/release/config.go
  pkg/release/pending.go
  pkg/release/values.go
  pkg/repo/config.go
Labels: size/L

#485 feat: allow to depend_on tag
  .changes/unreleased/New feature-20221021-194622.yaml
  pkg/release/config.go
  pkg/release/config_export_test.go
  pkg/release/config_test.go
  pkg/release/dependencies.go
  pkg/release/interface.go
Labels: size/M

#493 Release 0.24.0
  .changes/unreleased/Breaking change!-20221022-093305.yaml
  .github/workflows/goreleaser.yml
Labels: size/XS

#496 Release 0.24.0
  .changes/unreleased/Fixed-20221021-102719.yaml
  .github/workflows/goreleaser.yml
Labels: size/S
