Repository helmwave/helmwave, pull requests merged in 2022-08, with the labels that each got.

#384 Release 0.20.1
  .github/workflows/goreleaser.yml
  .github/workflows/notify.yml
  go.mod
  go.sum
Labels: size/S

#385 Release 0.20.2
  pkg/action/validate.go
  pkg/plan/apply.go
  pkg/plan/build_values.go
  pkg/plan/build_values_internal_test.go
  pkg/plan/import.go
  pkg/plan/validate.go
  pkg/plan/validate_test.go
  pkg/release/upgrade.go
  pkg/release/values.go
  pkg/release/values_test.go
  pkg/version/version.go
Labels: size/L

#386 Release 0.20.3
  pkg/plan/apply.go
Labels: size/XS

#389 feat: handle pending releases
  pkg/release/config.go
  pkg/release/pending.go
  pkg/release/upgrade.go
Labels: size/M

#388 fix: refactor kubedog a bit
  pkg/kubedog/manifest.go
  pkg/kubedog/multitrack.go
  pkg/plan/apply.go
Labels: size/M

#390 fix(ci): tune trivy workflow
  .github/workflows/container-analysis.yml
Labels: size/S

#387 Update Goreleaser config
  .github/workflows/goreleaser.yml
  .github/workflows/notify.yml
  .goreleaser.yml
  .pre-commit-config.yaml
  pkg/version/version.go
Labels: size/L

#398 fix: release-0.21.0 to release/0.21.0
  .github/workflows/goreleaser.yml
Labels: size/XS

#399 Release v0.21.0
  .github/workflows/container-analysis.yml
  .github/workflows/goreleaser.yml
  .github/workflows/notify.yml
  .goreleaser.yml
  .pre-commit-config.yaml
  go.mod
  go.sum
  pkg/helper/http.go
  pkg/kubedog/manifest.go
  pkg/kubedog/multitrack.go
  pkg/plan/apply.go
  pkg/release/config.go
  pkg/release/pending.go
  pkg/release/upgrade.go
  pkg/repo/install.go
  pkg/template/extra.go
  pkg/version/version.go
Labels: size/L

#404 Release 0.21.0
  .github/workflows/goreleaser.yml
  .goreleaser.yml
Labels: size/XS

#406 Release 0.21.0
  .github/workflows/goreleaser.yml
Labels: size/S

#407 fix(brew): tune homebrew test
  .github/workflows/goreleaser-test.yml
  .github/workflows/goreleaser.yml
  .goreleaser.yml
Labels: size/M

#408 feat: make namespace in depends_on optional
  pkg/plan/apply.go
  pkg/plan/apply_test.go
  pkg/plan/build_graph.go
  pkg/plan/build_releases.go
  pkg/plan/new_export_test.go
  pkg/release/chart_test.go
  pkg/release/config.go
  pkg/release/config_export_test.go
  pkg/release/config_test.go
  pkg/release/get_test.go
  pkg/release/interface.go
  pkg/release/list_test.go
  pkg/release/rollback_test.go
  pkg/release/status_test.go
  pkg/release/uninstall_test.go
  pkg/release/uniqname/uniqname.go
Labels: size/L

#411 fix: #410
  pkg/registry/install.go
Labels: size/S

#409 Release 0.21.1
  .github/workflows/goreleaser-test.yml
  .github/workflows/goreleaser.yml
  .goreleaser.yml
  pkg/plan/apply.go
  pkg/plan/apply_test.go
  pkg/plan/build_graph.go
  pkg/plan/build_releases.go
  pkg/plan/new_export_test.go
  pkg/registry/install.go
  pkg/release/chart_test.go
  pkg/release/config.go
  pkg/release/config_export_test.go
  pkg/release/config_test.go
  pkg/release/get_test.go
  pkg/release/interface.go
  pkg/release/list_test.go
  pkg/release/rollback_test.go
  pkg/release/status_test.go
  pkg/release/uninstall_test.go
  pkg/release/uniqname/uniqname.go
Labels: size/L

#419 feat: log error if kubedog without wait
  pkg/plan/apply.go
  pkg/plan/new_export_test.go
  pkg/release/config.go
  pkg/release/interface.go
Labels: size/S

#418 feat: generate full depends_on for planfile
  pkg/release/config.go
  pkg/release/config_test.go
  pkg/release/interface.go
  pkg/template/gomplate_templater.go
  pkg/template/tpl2yml_test.go
  tests/08_helmwave.yml
  tests/08_values.yaml
Labels: size/L

#424 feat: new yaml linter
  .github/workflows/yaml-int.yml
  .golangci.yml
  .yamllint.yaml
  codecov.yml
  tests/05_helmwave.yml
Labels: size/M

#423 Auto assign
  .github/auto-assign.yml
  .github/workflows/auto-assign.yml
Labels: size/M

#420 Release 0.22.0
  go.mod
  go.sum
  pkg/plan/apply.go
  pkg/plan/new_export_test.go
  pkg/release/config.go
  pkg/release/config_export_test.go
  pkg/release/config_test.go
  pkg/release/interface.go
  pkg/template/gomplate_templater.go
  pkg/template/tpl2yml_test.go
  tests/08_helmwave.yml
  tests/08_values.yaml
Labels: size/L

#426 feat: show diff for charts metadata
  go.mod
  go.sum
  pkg/plan/build_manifests.go
  pkg/plan/diff.go
  pkg/plan/new_export_test.go
  pkg/release/config_export_test.go
  pkg/release/config_test.go
  pkg/release/interface.go
  pkg/release/sync.go
  tests/02_helmwave.yml
Labels: size/M

#427 feat: warn on unused build flags
  pkg/action/interface.go
  pkg/action/up.go
Labels: size/S

#428 Release 0.22.1
  .github/workflows/goreleaser.yml
  go.mod
  go.sum
  pkg/action/interface.go
  pkg/action/up.go
  pkg/plan/build_manifests.go
  pkg/plan/diff.go
  pkg/plan/new_export_test.go
  pkg/release/config_export_test.go
  pkg/release/config_test.go
  pkg/release/interface.go
  pkg/release/sync.go
  tests/02_helmwave.yml
Labels: size/L

#437 feat: increase client ratelimit
  go.mod
  pkg/helper/helm.go
Labels: size/S

#438 Release/0.22.2
  .github/workflows/goreleaser.yml
  .goreleaser.yml
  go.mod
  go.sum
  pkg/helper/helm.go
Labels: size/M
