Repository helmwave/helmwave, pull requests merged in 2023-08, with the labels that each got.

#673 feat: tune homebrew formula
  .changes/unreleased/Other-20230802-234346.yaml
  .goreleaser.yml
  cmd/helmwave/completion.go
Labels: size/XS

#674 fix: fix missing completions
  .goreleaser.yml
Labels: size/XS

#676 feat: automatically set offline_kube_version
  .changes/unreleased/New feature-20230804-173623.yaml
  pkg/action/build_internal_test.go
  pkg/helper/helm.go
  pkg/release/upgrade.go
  tests/15_helmwave.yml
Labels: size/S

#677 Release 0.30.1
  .changes/unreleased/New feature-20230804-173623.yaml
  .github/workflows/go-tests.yml
  .github/workflows/goreleaser.yml
  pkg/action/diff_internal_test.go
  pkg/helper/helm.go
  pkg/release/chart_test.go
  pkg/release/get_test.go
  pkg/release/sync_test.go
  pkg/release/upgrade.go
Labels: size/S

#679 Update CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: size/S

#682 Release 0.30.2
  .changes/unreleased/Fixed-20230815-015113.yaml
  .changes/unreleased/New feature-20230815-015307.yaml
  .github/workflows/go-lint.yml
  .golangci.yml
  go.mod
  go.sum
  pkg/action/build_internal_test.go
  pkg/cache/charts.go
  pkg/cache/errors.go
  pkg/helper/helm.go
  pkg/hooks/env.go
  pkg/hooks/errors.go
  pkg/hooks/yaml.go
  pkg/plan/build_registries.go
  pkg/plan/build_releases.go
  pkg/plan/build_repos.go
  pkg/plan/diff.go
  pkg/plan/errors.go
  pkg/plan/import.go
  pkg/plan/kubedog.go
  pkg/plan/new.go
  pkg/plan/new_export_test.go
  pkg/plan/rollback.go
  pkg/plan/up.go
  pkg/plan/validate.go
  pkg/plan/validate_test.go
  pkg/registry/config.go
  pkg/registry/errors.go
  pkg/registry/interface.go
  pkg/release/config.go
  pkg/release/config_test.go
  pkg/release/dependencies.go
  pkg/release/errors.go
  pkg/release/interface.go
  pkg/release/pending.go
  pkg/release/uniqname/errors.go
  pkg/release/uniqname/uniqname.go
  pkg/release/uniqname/uniqname_test.go
  pkg/release/validate.go
  pkg/release/validate_test.go
  pkg/release/values.go
  pkg/repo/config.go
  pkg/repo/config_export_test.go
  pkg/repo/errors.go
  pkg/repo/interface.go
  pkg/repo/validate.go
  pkg/repo/validate_test.go
Labels: size/M

#689 feat: add per-release flag to show notes
  .changes/unreleased/New feature-20230821-121433.yaml
  pkg/release/config.go
  pkg/release/sync.go
Labels: size/XS

#690 Release 0.31.0
  .changes/unreleased/New feature-20230821-121433.yaml
  pkg/cache/charts.go
  pkg/cache/errors.go
  pkg/hooks/errors.go
  pkg/hooks/run.go
  pkg/hooks/yaml.go
  pkg/log/errors.go
  pkg/log/log.go
  pkg/plan/build_registries.go
  pkg/plan/build_releases.go
  pkg/plan/build_repos.go
  pkg/plan/validate.go
  pkg/registry/errors.go
  pkg/registry/install.go
  pkg/registry/interface.go
  pkg/release/chart.go
  pkg/release/chart_test.go
  pkg/release/config.go
  pkg/release/config_test.go
  pkg/release/dependencies.go
  pkg/release/errors.go
  pkg/release/sync.go
  pkg/release/uniqname/errors.go
  pkg/release/uniqname/uniqname.go
  pkg/release/validate.go
  pkg/repo/errors.go
  pkg/repo/validate.go
Labels: size/M

#698 fix: pass some release options to down action
  .changes/unreleased/Fixed-20230827-184615.yaml
  .github/workflows/go-lint.yml
  pkg/cache/errors.go
  pkg/hooks/errors.go
  pkg/log/errors.go
  pkg/registry/errors.go
  pkg/release/config.go
  pkg/release/errors.go
  pkg/release/helm_actions.go
  pkg/release/pending.go
  pkg/release/uninstall.go
  pkg/release/uniqname/errors.go
  pkg/repo/errors.go
Labels: size/S

#699 fix!: no longer fail on empty plan
  .changes/unreleased/Breaking change!-20230828-002750.yaml
  pkg/plan/errors.go
  pkg/plan/import.go
  pkg/plan/validate.go
  pkg/plan/validate_test.go
Labels: size/XS

#700 feat: add support for new annotations and improve kubedog errors
  .changes/unreleased/New feature-20230828-010105.yaml
  .changes/unreleased/New feature-20230828-010145.yaml
  pkg/helper/const.go
  pkg/kubedog/annotations.go
  pkg/kubedog/errors.go
  pkg/kubedog/multitrack.go
Labels: size/S

#701 fix: filter unused repositories and registries
  .changes/unreleased/Fixed-20230828-011451.yaml
  pkg/plan/build.go
Labels: size/XS

#702 Release 0.31.1
  .changes/unreleased/Breaking change!-20230828-002750.yaml
  .changes/unreleased/Fixed-20230827-184615.yaml
  .changes/unreleased/Fixed-20230828-011451.yaml
  .changes/unreleased/New feature-20230828-010105.yaml
  .changes/unreleased/New feature-20230828-010145.yaml
  .github/workflows/go-lint.yml
  pkg/cache/errors.go
  pkg/helper/const.go
  pkg/hooks/errors.go
  pkg/kubedog/annotations.go
  pkg/kubedog/errors.go
  pkg/kubedog/multitrack.go
  pkg/log/errors.go
  pkg/plan/build.go
  pkg/plan/errors.go
  pkg/plan/import.go
  pkg/plan/validate.go
  pkg/plan/validate_test.go
  pkg/registry/errors.go
  pkg/release/config.go
  pkg/release/errors.go
  pkg/release/helm_actions.go
  pkg/release/pending.go
  pkg/release/uninstall.go
  pkg/release/uniqname/errors.go
  pkg/repo/errors.go
Labels: size/M
