Repository helmwave/helmwave, pull requests merged in 2023-07, with the labels that each got.

#653 fix: improve plan validation
  .changes/v0.29.4.md
  CHANGELOG.md
  pkg/action/build_internal_test.go
  pkg/action/yml_internal_test.go
  pkg/plan/build.go
  pkg/plan/build_releases.go
  pkg/plan/import.go
  pkg/plan/new.go
  pkg/plan/validate.go
  tests/14_helmwave.yml
Labels: size/S

#650 fix: tune graph cells width
  .changes/unreleased/Fixed-20230630-125521.yaml
  .changes/unreleased/Fixed-20230630-125607.yaml
  pkg/plan/build_graph.go
Labels: size/XS

#656 Release/0.29.4
  .changes/unreleased/Fixed-20230630-125521.yaml
  .changes/unreleased/Fixed-20230630-125607.yaml
  .changes/v0.29.4.md
  CHANGELOG.md
  pkg/action/build_internal_test.go
  pkg/action/yml_internal_test.go
  pkg/plan/build.go
  pkg/plan/build_graph.go
  pkg/plan/build_releases.go
  pkg/plan/import.go
  pkg/plan/new.go
  pkg/plan/validate.go
  tests/14_helmwave.yml
Labels: size/S

#663 feat: add support for tracking generic resources
  .changes/unreleased/New feature-20230724-121146.yaml
  pkg/action/flags.go
  pkg/action/up.go
  pkg/kubedog/config.go
  pkg/kubedog/manifest.go
  pkg/kubedog/multitrack.go
  pkg/plan/up.go
Labels: size/S

#664 feat: add support for kubedog in rollback
  .changes/unreleased/New feature-20230724-121455.yaml
  pkg/action/rollback.go
  pkg/plan/diff.go
  pkg/plan/new_export_test.go
  pkg/plan/rollback.go
  pkg/plan/rollback_test.go
  pkg/release/get.go
  pkg/release/get_test.go
  pkg/release/interface.go
Labels: size/S

#667 Add some kubedog tests
  pkg/kubedog/multitrack_test.go
  pkg/plan/kubedog.go
  pkg/plan/kubedog_internal_test.go
  pkg/plan/rollback.go
  pkg/plan/up.go
Labels: size/M

#666 fix: update dependencies while building releases
  .changes/unreleased/Fixed-20230724-180144.yaml
  pkg/plan/build_releases.go
  pkg/plan/new_export_test.go
  pkg/release/config.go
  pkg/release/interface.go
Labels: size/XS

#665 Release 0.30.0
  .changes/unreleased/Fixed-20230724-180144.yaml
  .changes/unreleased/New feature-20230724-121146.yaml
  .changes/unreleased/New feature-20230724-121455.yaml
  pkg/action/flags.go
  pkg/action/rollback.go
  pkg/action/up.go
  pkg/kubedog/config.go
  pkg/kubedog/manifest.go
  pkg/kubedog/multitrack.go
  pkg/kubedog/multitrack_test.go
  pkg/plan/build_releases.go
  pkg/plan/diff.go
  pkg/plan/kubedog.go
  pkg/plan/kubedog_internal_test.go
  pkg/plan/new_export_test.go
  pkg/plan/rollback.go
  pkg/plan/rollback_test.go
  pkg/plan/up.go
  pkg/release/config.go
  pkg/release/get.go
  pkg/release/get_test.go
  pkg/release/interface.go
Labels: size/M

#671 feat: add utm parameters to docs links
  README.md
Labels: size/XS
