Repository helmwave/helmwave, pull requests merged in 2023-06, with the labels that each got.

#600 fix: homebrew tap repo for case-sensitive systems
  .changes/unreleased/Fixed-20230602-173911.yaml
  .goreleaser.yml
Labels: size/XS

#598 Add skip-unchanged flag
  go.mod
  go.sum
  pkg/action/build.go
  pkg/plan/diff.go
  pkg/plan/export.go
  pkg/plan/new.go
Labels: size/M

#587 fix: lint nolint
  .github/stale.yml
  .github/workflows/go-lint.yml
  .github/workflows/go-tests.yml
  .github/workflows/goreleaser.yml
  .gitignore
  .golangci.yml
  cmd/helmwave/completion.go
  cmd/helmwave/main.go
  pkg/action/build_internal_test.go
  pkg/action/diff_live_internal_test.go
  pkg/action/diff_plan_internal_test.go
  pkg/action/down_internal_test.go
  pkg/action/interface.go
  pkg/action/status_internal_test.go
  pkg/action/up_internal_test.go
  pkg/action/yml_internal_test.go
  pkg/cache/charts_cache.go
  pkg/helper/helm.go
  pkg/helper/kubedog_test.go
  pkg/helper/yml.go
  pkg/kubedog/multitrack.go
  pkg/log/log.go
  pkg/log/log_internal_test.go
  pkg/plan/apply.go
  pkg/plan/apply_test.go
  pkg/plan/build.go
  pkg/plan/build_releases.go
  pkg/plan/diff.go
  pkg/plan/list.go
  pkg/plan/new.go
  pkg/registry/config.go
  pkg/release/chart.go
  pkg/release/chart_test.go
  pkg/release/config.go
  pkg/release/dependencies.go
  pkg/release/get.go
  pkg/release/get_test.go
  pkg/release/pending.go
  pkg/release/values.go
  pkg/repo/config.go
  pkg/template/extra.go
  pkg/template/extra_test.go
  pkg/template/gomplate_templater.go
  pkg/template/no_templater.go
  pkg/template/sprig_templater.go
  pkg/template/tpl2yml.go
  pkg/version/version.go
Labels: size/L

#603 Release 0.26.0
  .github/stale.yml
  .github/workflows/go-lint.yml
  .github/workflows/go-tests.yml
  .github/workflows/goreleaser.yml
  .gitignore
  .golangci.yml
  cmd/helmwave/completion.go
  cmd/helmwave/main.go
  pkg/action/build_internal_test.go
  pkg/action/diff_live_internal_test.go
  pkg/action/diff_plan_internal_test.go
  pkg/action/down_internal_test.go
  pkg/action/interface.go
  pkg/action/status_internal_test.go
  pkg/action/up_internal_test.go
  pkg/action/yml_internal_test.go
  pkg/cache/charts_cache.go
  pkg/helper/helm.go
  pkg/helper/kubedog_test.go
  pkg/helper/yml.go
  pkg/kubedog/multitrack.go
  pkg/log/log.go
  pkg/log/log_internal_test.go
  pkg/plan/apply.go
  pkg/plan/apply_test.go
  pkg/plan/build.go
  pkg/plan/build_releases.go
  pkg/plan/diff.go
  pkg/plan/list.go
  pkg/plan/new.go
  pkg/registry/config.go
  pkg/release/chart.go
  pkg/release/chart_test.go
  pkg/release/config.go
  pkg/release/dependencies.go
  pkg/release/get.go
  pkg/release/get_test.go
  pkg/release/pending.go
  pkg/release/values.go
  pkg/repo/config.go
  pkg/template/extra.go
  pkg/template/extra_test.go
  pkg/template/gomplate_templater.go
  pkg/template/no_templater.go
  pkg/template/sprig_templater.go
  pkg/template/tpl2yml.go
  pkg/version/version.go
Labels: size/L

#605 Release/0.26.0
  .changes/unreleased/CI-20230421-164146.yaml
  .changes/v0.26.0.md
  .github/workflows/goreleaser.yml
Labels: size/S

#607 Fix rm dist
  .changes/v0.26.0.md
  .github/workflows/goreleaser.yml
Labels: size/XS

#601 Release 0.27.0
  .changes/unreleased/Fixed-20230602-173911.yaml
  .changes/unreleased/New feature-20230604-135036.yaml
  .goreleaser.yml
  go.mod
  go.sum
  pkg/action/build.go
  pkg/plan/diff.go
  pkg/plan/export.go
  pkg/plan/new.go
  pkg/release/config.go
  pkg/template/extra_test.go
Labels: size/L

#611 Release/0.27.1
  .changes/unreleased/Fixed-20230608-145632.yaml
  .changes/unreleased/New feature-20230608-145525.yaml
  .changes/unreleased/New feature-20230608-145815.yaml
  .changes/unreleased/New feature-20230608-145910.yaml
  .changes/unreleased/New feature-20230608-150121.yaml
  .changes/unreleased/Other-20230608-150038.yaml
  .changes/v0.27.1.md
  .pre-commit-config.yaml
  cmd/helmwave/main.go
  go.mod
  go.sum
  pkg/action/build.go
  pkg/action/build_internal_test.go
  pkg/action/diff.go
  pkg/action/flags.go
  pkg/action/up.go
  pkg/kubedog/silence.go
  pkg/log/log.go
  pkg/log/log_internal_test.go
  pkg/plan/apply.go
  pkg/plan/build.go
  pkg/plan/build_graph.go
  pkg/plan/diff.go
  pkg/release/config.go
  pkg/release/install.go
  pkg/release/upgrade.go
  tests/12_helmwave.yml
  tests/12_values.yaml
Labels: size/L

#615 feat: offline_kube_ver
  .changes/unreleased/New feature-20230609-204622.yaml
  pkg/log/log.go
  pkg/log/log_internal_test.go
  pkg/plan/new_export_test.go
  pkg/release/config.go
  pkg/release/interface.go
  tests/12_helmwave.yml
Labels: size/M

#620 Release/0.27.4
  .changes/unreleased/Dependencies-20230616-183115.yaml
  .changes/unreleased/Other-20230616-183217.yaml
  cmd/helmwave/main.go
  pkg/action/build.go
  pkg/action/diff.go
  pkg/action/diff_live.go
  pkg/action/diff_plan.go
  pkg/action/down.go
  pkg/action/flags.go
  pkg/action/graph.go
  pkg/action/jsonschema.go
  pkg/action/list.go
  pkg/action/rollback.go
  pkg/action/status.go
  pkg/action/up.go
  pkg/action/validate.go
  pkg/action/yml.go
  pkg/log/log.go
  pkg/release/chart.go
Labels: size/M

#627 Release 0.28.0
  .changes/unreleased/New feature-20230617-041635.yaml
  .changes/unreleased/New feature-20230617-043909.yaml
  .changes/unreleased/New feature-20230617-054619.yaml
  go.mod
  go.sum
  pkg/action/down.go
  pkg/action/up.go
  pkg/hooks/config.go
  pkg/hooks/lifecycle.go
  pkg/hooks/yaml.go
  pkg/kubedog/config.go
  pkg/kubedog/silence.go
  pkg/log/log_internal_test.go
  pkg/plan/build.go
  pkg/plan/down.go
  pkg/plan/down_test.go
  pkg/plan/new.go
  pkg/plan/rollback.go
  pkg/plan/up.go
  pkg/plan/up_test.go
  pkg/release/config.go
  pkg/release/rollback.go
  pkg/release/sync.go
  pkg/release/uninstall.go
  tests/13_helmwave.yml
Labels: size/XL

#634 Chart options copy
  CONTRIBUTING.md
  Dockerfile
  README.md
  pkg/release/chart.go
  pkg/release/config.go
Labels: size/M

#635 Add test chart fields
  pkg/plan/export.go
  pkg/plan/new_export_test.go
  pkg/plan/up.go
  pkg/release/chart.go
  pkg/release/chart_internal_test.go
  pkg/release/config.go
  pkg/release/config_internal_test.go
  pkg/release/interface.go
  pkg/release/is_installed.go
  pkg/release/repo.go
  pkg/release/uniqname/uniqname.go
Labels: size/L

#633 Release 0.28.1
  .changes/unreleased/Fixed-20230622-133230.yaml
  .changes/unreleased/New feature-20230623-151709.yaml
  .github/workflows/hadolint.yml
  CONTRIBUTING.md
  Dockerfile
  README.md
  pkg/action/diff.go
  pkg/action/diff_local.go
  pkg/action/diff_plan_internal_test.go
  pkg/cache/charts.go
  pkg/hooks/config.go
  pkg/hooks/run.go
  pkg/plan/build_repos_internal_test.go
  pkg/plan/export.go
  pkg/plan/import.go
  pkg/plan/new.go
  pkg/plan/new_export_test.go
  pkg/plan/up.go
  pkg/plan/validate.go
  pkg/registry/config.go
  pkg/release/chart.go
  pkg/release/chart_internal_test.go
  pkg/release/config.go
  pkg/release/config_internal_test.go
  pkg/release/interface.go
  pkg/release/is_installed.go
  pkg/release/repo.go
  pkg/release/uniqname/uniqname.go
  pkg/version/version.go
Labels: size/L

#637 feat: fail on failed hooks and pass some envs to commands
  .changes/unreleased/Breaking change!-20230627-213322.yaml
  .changes/unreleased/New feature-20230627-213341.yaml
  .changes/unreleased/New feature-20230627-213405.yaml
  pkg/action/rollback.go
  pkg/helper/context.go
  pkg/hooks/config.go
  pkg/hooks/env.go
  pkg/hooks/run.go
  pkg/plan/build.go
  pkg/plan/down.go
  pkg/plan/new_export_test.go
  pkg/plan/rollback.go
  pkg/plan/rollback_test.go
  pkg/plan/up.go
  pkg/release/interface.go
  pkg/release/pending.go
  pkg/release/rollback.go
  pkg/release/rollback_test.go
  pkg/release/sync.go
  pkg/release/uninstall.go
Labels: size/L

#639 Add tests for lifecycle hooks
  pkg/helper/context_test.go
  pkg/hooks/config.go
  pkg/hooks/config_export_test.go
  pkg/hooks/interface.go
  pkg/hooks/run.go
  pkg/hooks/run_test.go
  pkg/hooks/yaml.go
  pkg/hooks/yaml_test.go
Labels: size/L

#640 feat: allow skipping repo refresh during dep update
  .changes/unreleased/New feature-20230628-120859.yaml
  pkg/release/chart.go
  pkg/release/upgrade.go
Labels: size/M

#638 Release 0.29.0
  .changes/unreleased/Breaking change!-20230627-213322.yaml
  .changes/unreleased/New feature-20230627-213341.yaml
  .changes/unreleased/New feature-20230627-213405.yaml
  .changes/unreleased/New feature-20230628-120859.yaml
  pkg/action/build_internal_test.go
  pkg/action/rollback.go
  pkg/helper/context.go
  pkg/helper/context_test.go
  pkg/hooks/config.go
  pkg/hooks/config_export_test.go
  pkg/hooks/env.go
  pkg/hooks/interface.go
  pkg/hooks/run.go
  pkg/hooks/run_test.go
  pkg/hooks/yaml.go
  pkg/hooks/yaml_test.go
  pkg/plan/build.go
  pkg/plan/down.go
  pkg/plan/new_export_test.go
  pkg/plan/rollback.go
  pkg/plan/rollback_test.go
  pkg/plan/up.go
  pkg/release/chart.go
  pkg/release/config.go
  pkg/release/interface.go
  pkg/release/pending.go
  pkg/release/rollback.go
  pkg/release/rollback_test.go
  pkg/release/sync.go
  pkg/release/uninstall.go
  pkg/release/upgrade.go
Labels: size/XL

#642 Release 0.29.1
  .changes/unreleased/Breaking change!-20230628-135708.yaml
  .changes/unreleased/New feature-20230628-135725.yaml
  pkg/release/chart.go
Labels: size/S

#644 fix: properly handle values strict flag
  .changes/unreleased/Fixed-20230629-131127.yaml
  pkg/release/values.go
Labels: size/S

#649 chore(ci): tune goreleaser
  .goreleaser.yml
Labels: size/XS
