Repository helmwave/helmwave, pull requests merged in 2023-11, with the labels that each got.

#771 Fix some 0.32.2
  .changes/unreleased/Dependencies-20231101-004140.yaml
  .changes/unreleased/Fixed-20231101-004120.yaml
  go.mod
  go.sum
Labels: size/S

#762 Upgrade Helm to 3.13.0 (Fix Test Cases)
  .changes/unreleased/Dependencies-20231014-134104.yaml
  pkg/release/chart.go
  pkg/release/config.go
  pkg/release/config_internal_test.go
  pkg/release/helm_actions.go
Labels: size/XS

#758 Release/0.32.2
  .changes/unreleased/Dependencies-20231014-134104.yaml
  .changes/unreleased/Dependencies-20231101-004140.yaml
  .changes/unreleased/Fixed-20231101-004120.yaml
  go.mod
  go.sum
  pkg/action/flags.go
  pkg/release/chart.go
  pkg/release/config.go
  pkg/release/config_internal_test.go
  pkg/release/helm_actions.go
Labels: size/M

#755 Add support for using .env file
  .changes/unreleased/New feature-20231014-135306.yaml
  .changes/v0.32.2.md
  .github/workflows/container-analysis.yml
  .github/workflows/gitleaks.yml
  CHANGELOG.md
  cmd/helmwave/main.go
  go.mod
  go.sum
  pkg/action/flags.go
  pkg/release/chart.go
  pkg/release/config.go
  pkg/release/config_internal_test.go
  pkg/release/helm_actions.go
Labels: size/M

#773 Release/0.32.3
  .changes/unreleased/Fixed-20231101-054337.yaml
  pkg/plan/build_repos.go
  pkg/plan/build_repos_internal_test.go
Labels: size/XS

#785 chore: set up qodana code quality
  .changes/unreleased/CI-20231116-211600.yaml
  .github/workflows/qodana.yml
  qodana.yaml
Labels: size/XS
