Repository helmwave/helmwave, pull requests merged in 2024-04, with the labels that each got.

#859 feat: bump go 1.22 && bump deps
  go.mod
  go.sum
Labels: size/L

#862 feat: go 1.22
  .changes/unreleased/Dependencies-20240426-120118.yaml
  .github/workflows/go-lint.yml
  .github/workflows/go-tests.yml
  .github/workflows/goreleaser.yml
  .goreleaser.yml
  Dockerfile
Labels: size/XS

#864 feat: allow to reference other values
  .changes/unreleased/Breaking change!-20240428-000128.yaml
  .changes/unreleased/New feature-20240427-233626.yaml
  .changes/unreleased/New feature-20240428-000050.yaml
  .github/workflows/go-lint.yml
  cmd/helmwave/completion_internal_test.go
  pkg/action/build_internal_test.go
  pkg/kubedog/multitrack.go
  pkg/plan/up.go
  pkg/plan/validate_test.go
  pkg/release/values.go
  pkg/template/gomplate_templater.go
  pkg/template/no_templater.go
  pkg/template/sops_templater.go
  pkg/template/sprig_templater.go
  pkg/template/tpl2yml.go
  tests/19_helmwave.yml
  tests/19_values_1.yaml
  tests/19_values_2.yaml
Labels: size/M

#865 fix: do not run hooks during charts diff
  .changes/unreleased/Fixed-20240428-002353.yaml
  pkg/plan/build_manifests.go
  pkg/plan/diff.go
  pkg/plan/mock_release_export_test.go
  pkg/plan/up.go
  pkg/release/get_test.go
  pkg/release/interface.go
  pkg/release/sync.go
  pkg/release/sync_test.go
Labels: size/XS

#854 ✨ feat: create a new debug tag for docker image with extra tools for hook/lifecycle command usages
  .goreleaser.yml
  Dockerfile
Labels: size/XS
