Repository helmwave/helmwave, pull requests merged in 2024-05, with the labels that each got.

#871 Release/0.36.1
  .changes/unreleased/Fixed-20240501-114043.yaml
  pkg/release/chart.go
Labels: size/XS

#873 Release 0.36.2
  .changes/unreleased/Fixed-20240502-140825.yaml
  pkg/release/chart.go
Labels: size/XS

#876 fix: persist values order
  .changes/unreleased/Fixed-20240508-102022.yaml
  .github/workflows/go-lint.yml
  .golangci.yml
  pkg/release/values.go
Labels: size/XS

#877 chore: refactor context funcs into separate package
  pkg/action/interface.go
  pkg/action/up.go
  pkg/clictx/clictx.go
  pkg/plan/up.go
Labels: size/XS

#879 Follow reverse dependency order while uninstalling
  .changes/unreleased/New feature-20231014-141808.yaml
  .changes/unreleased/New feature-20231014-141841.yaml
  pkg/plan/down.go
  pkg/plan/down_test.go
  pkg/plan/up.go
  pkg/release/config.go
  pkg/release/dependency/graph.go
  pkg/release/dependency/graph_test.go
  pkg/release/helm_actions.go
Labels: size/S

#880 Release 0.36.3
  .changes/unreleased/Fixed-20240508-102022.yaml
  .changes/unreleased/New feature-20231014-141808.yaml
  .changes/unreleased/New feature-20231014-141841.yaml
  .github/workflows/go-lint.yml
  .github/workflows/qodana.yml
  .golangci.yml
  pkg/action/interface.go
  pkg/action/up.go
  pkg/clictx/clictx.go
  pkg/plan/down.go
  pkg/plan/down_test.go
  pkg/plan/up.go
  pkg/release/config.go
  pkg/release/dependency/graph.go
  pkg/release/dependency/graph_test.go
  pkg/release/get.go
  pkg/release/helm_actions.go
  pkg/release/interface.go
  pkg/release/is_installed.go
  pkg/release/list.go
  pkg/release/monitors.go
  pkg/release/rollback.go
  pkg/release/status.go
  pkg/release/sync.go
  pkg/release/uninstall.go
  pkg/release/upgrade.go
  pkg/release/validate.go
  pkg/release/values.go
  pkg/repo/in.go
  pkg/repo/in_test.go
Labels: size/M

#893 fix: jsonschema to validate values
  .changes/unreleased/Fixed-20240530-211514.yaml
  .github/workflows/go-lint.yml
  .golangci.yml
  pkg/release/config.go
  pkg/release/values.go
Labels: size/XS

#894 Release/0.36.4
  .changes/unreleased/Fixed-20240530-211514.yaml
  .github/workflows/go-lint.yml
  .golangci.yml
  pkg/release/config.go
  pkg/release/values.go
Labels: size/XS
