Repository helmwave/helmwave, pull requests merged in 2024-09, with the labels that each got.

#965 fix: go lint
  .github/workflows/goreleaser.yml
  cmd/gitops/main.go
  cmd/helmwave/main.go
  pkg/action/manifests.go
  pkg/clictx/clictx.go
Labels: size/XS

#967 Release/0.40.1
  .changes/unreleased/CI-20240903-183938.yaml
  .github/workflows/auto-assign.yml
  .github/workflows/changelog-check.yml
  .github/workflows/changelog.yml
  .github/workflows/container-analysis.yml
  .github/workflows/docs.yml
  .github/workflows/gitleaks.yml
  .github/workflows/go-lint.yml
  .github/workflows/go-tests.yml
  .github/workflows/goreleaser-check.yml
  .github/workflows/goreleaser.yml
  .github/workflows/hadolint.yml
  .github/workflows/json-schema.yml
  .github/workflows/release-tag.yml
  .goreleaser.yml
Labels: size/M

#968 fix(ci): anchors
  .github/workflows/go-tests.yml
Labels: size/XS

#969 fix(ci): PAT
  .github/workflows/release-tag.yml
Labels: size/XS

#970 fix(ci): disable changelog in goreleaser.yml
  .github/workflows/goreleaser.yml
  .goreleaser.yml
Labels: size/XS

#971 release/0.40.1
  .github/workflows/release-tag.yml
Labels: size/XS

#973 release/0.40.1
  .github/workflows/release-tag.yml
Labels: size/XS

#974 release/0.40.1
  .github/workflows/release-tag.yml
Labels: size/XS

#975 release/0.40.1
  .github/workflows/release-tag.yml
Labels: size/XS

#976 release/0.40.1
  .github/workflows/release-tag.yml
Labels: size/XS

#977 release/0.40.1
  .goreleaser.yml
Labels: size/XS

#978 release/0.40.1
  .goreleaser.yml
Labels: size/XS

#979 Release/0.40.2
  .changes/unreleased/CI-20240903-232436.yaml
  .github/workflows/changelog-check.yml
  .github/workflows/docs.yml
  .github/workflows/go-lint.yml
  .github/workflows/go-tests.yml
  .github/workflows/goreleaser-check.yml
  .github/workflows/goreleaser.yml
  .github/workflows/hadolint.yml
  .github/workflows/release-tag.yml
  .github/workflows/yaml-lint.yml
Labels: size/XS

#981 Release/0.40.3
  .changes/unreleased/Fixed-20240904-010406.yaml
  pkg/action/jsonschema.go
Labels: size/XS

#982 fix: changelog
  CHANGELOG.md
Labels: size/XS

#986 Release/0.40.5
  .changes/unreleased/CI-20240904-022808.yaml
  .github/workflows/changelog.yml
  .github/workflows/go-lint.yml
  .github/workflows/go-tests.yml
  .github/workflows/hadolint.yml
  .github/workflows/qodana.yml
Labels: size/XS

#988 Release/0.40.5
  .changes/unreleased/CI-20240904-031959.yaml
  .changes/unreleased/Dependencies-20240904-032031.yaml
  .changes/unreleased/Fixed-20240904-113614.yaml
  .github/CODEOWNERS
  .github/workflows/auto-assign.yml
  .github/workflows/changelog-check.yml
  .github/workflows/changelog.yml
  .github/workflows/codeql.yml
  .github/workflows/container-check.yml
  .github/workflows/git-mirror.yml
  .github/workflows/gitleaks.yml
  .github/workflows/go-lint.yml
  .github/workflows/go-tests.yml
  .github/workflows/goreleaser-check.yml
  .github/workflows/goreleaser.yml
  .github/workflows/hadolint.yml
  .github/workflows/json-schema.yml
  .github/workflows/qodana.yml
  .github/workflows/yaml-lint.yml
  .goreleaser.yml
  .yamllint.yaml
  CONTRIBUTING.md
  Dockerfile
  go.mod
  go.sum
  pkg/action/jsonschema.go
  pkg/clictx/clictx.go
  pkg/clictx/clictx_test.go
  pkg/log/log.go
Labels: size/M

#993 feat(ci): dependabot approve & merge
  .github/workflows/dependabot.yml
Labels: size/XS

#995 Release/0.40.6
  .changes/unreleased/Dependencies-20240907-173307.yaml
  .changes/unreleased/Dependencies-20240907-175810.yaml
  .changes/unreleased/Dependencies-20240907-202718.yaml
  .github/workflows/changelog.yml
  go.mod
  go.sum
Labels: size/XS

#997 Release/0.40.7
  .changes/unreleased/Dependencies-20240908-015740.yaml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/dependabot.yml
  .github/workflows/changelog.yml
  .github/workflows/release-label.yml
  .github/workflows/release-tag.yml
  go.mod
  go.sum
  pkg/template/gomplate_templater.go
Labels: size/S, release, v0.40.7

#998 feat: make prometheus monitor human-friendly
  .changes/unreleased/New feature-20240908-001424.yaml
  .changie.yaml
  pkg/monitor/prometheus/config.go
  pkg/monitor/prometheus/errors.go
Labels: size/S

#999 Release/0.41.0
  .changes/unreleased/New feature-20240908-001424.yaml
  .changie.yaml
  .github/workflows/go-tests.yml
  pkg/action/up_internal_test.go
  pkg/monitor/prometheus/config.go
  pkg/monitor/prometheus/errors.go
  tests/20_helmwave.yml
  tests/20_values.yaml
  tests/kind-config.yaml
Labels: size/S, release, v0.41.0

#1000 Changelog/0.41.0
  .changes/unreleased/New feature-20240908-001424.yaml
  .changes/v0.41.0.md
  .github/workflows/changelog.yml
  .github/workflows/json-schema.yml
  CHANGELOG.md
Labels: size/XS, changelog, v0.41.0

#1009 Release/0.41.1
  .changes/unreleased/Breaking change!-20240921-200430.yaml
  .changes/unreleased/Dependencies-20240912-225734.yaml
  .changes/unreleased/Dependencies-20240912-225738.yaml
  .changes/unreleased/Dependencies-20240917-224150.yaml
  .changes/unreleased/Fixed-20240910-212657.yaml
  .changes/unreleased/New feature-20240921-200920.yaml
  .github/workflows/qodana.yml
  go.mod
  go.sum
  pkg/release/config.go
  pkg/release/helm_actions.go
  pkg/release/sync.go
  pkg/template/gomplate_templater.go
  pkg/template/sops_templater.go
Labels: size/S, release, v0.41.1

#1015 changelog/0.41.1
  .changes/unreleased/Breaking change!-20240921-200430.yaml
  .changes/unreleased/Dependencies-20240912-225734.yaml
  .changes/unreleased/Dependencies-20240912-225738.yaml
  .changes/unreleased/Dependencies-20240917-224150.yaml
  .changes/unreleased/Fixed-20240910-212657.yaml
  .changes/unreleased/New feature-20240921-200920.yaml
  .changes/v0.41.1.md
Labels: size/XS
