Repository helmwave/helmwave, pull requests merged in 2024-06, with the labels that each got.

#897 fix: ci for dependabot prs
  .github/workflows/auto-assign.yml
  .github/workflows/changelog-check.yml
  .github/workflows/git-mirror.yml
  .github/workflows/gitleaks.yml
  .github/workflows/go-lint.yml
  .github/workflows/go-tests.yml
  .github/workflows/goreleaser-test.yml
  .github/workflows/goreleaser.yml
  .github/workflows/hadolint.yml
  .github/workflows/qodana.yml
Labels: size/XS

#905 Release/0.37.0
  .changes/unreleased/New feature-20240617-223532.yaml
  .changes/unreleased/Other-20240617-223752.yaml
  pkg/action/build.go
  pkg/action/diff.go
  pkg/action/flags.go
Labels: size/XS

#912 fix: bump golang & deps & alpine
  .changes/unreleased/Dependencies-20240626-000958.yaml
  Dockerfile
  go.mod
  go.sum
  pkg/plan/mock_release_export_test.go
  pkg/release/config.go
  pkg/release/config_internal_test.go
  pkg/release/helm_actions.go
  pkg/release/interface.go
Labels: size/M

#913 feat: add flag to disable dependencies
  .changes/unreleased/New feature-20240625-231939.yaml
  pkg/action/build.go
  pkg/plan/build.go
  pkg/plan/build_releases.go
  pkg/plan/build_releases_internal_test.go
  pkg/release/config.go
Labels: size/S

#917 feat: respect release context in uniqname
  .changes/unreleased/Breaking change!-20240626-162240.yaml
  go.mod
  pkg/action/build_internal_test.go
  pkg/helper/context.go
  pkg/helper/context_test.go
  pkg/helper/helm.go
  pkg/helper/helm_test.go
  pkg/plan/build_manifests_internal_test.go
  pkg/plan/build_releases_internal_test.go
  pkg/plan/build_repos_internal_test.go
  pkg/plan/import.go
  pkg/plan/kubedog_internal_test.go
  pkg/plan/mock_release_export_test.go
  pkg/plan/new_test.go
  pkg/plan/status_test.go
  pkg/plan/up_test.go
  pkg/plan/validate_test.go
  pkg/release/config.go
  pkg/release/config_test.go
  pkg/release/dependencies.go
  pkg/release/helm_actions.go
  pkg/release/uniqname/uniqname.go
  pkg/release/uniqname/uniqname_test.go
  tests/01_helmwave.yml.tpl
Labels: size/S

#918 feat: refactor EnvVars for flags & find-renames: 1
  .changes/unreleased/New feature-20240626-185727.yaml
  pkg/action/build.go
  pkg/action/diff.go
  pkg/action/diff_local.go
  pkg/action/flags.go
  pkg/action/up.go
Labels: size/XS

#922 fix: uniqname validation error
  pkg/release/config_test.go
  pkg/release/uniqname/errors.go
  pkg/release/uniqname/uniqname.go
  pkg/release/uniqname/uniqname_test.go
  pkg/release/validate_test.go
Labels: size/XS

#914 Release/0.38.0
  .changes/unreleased/Breaking change!-20240626-162240.yaml
  .changes/unreleased/New feature-20240625-231939.yaml
  .changes/unreleased/New feature-20240626-185727.yaml
  go.mod
  pkg/action/build.go
  pkg/action/build_internal_test.go
  pkg/action/diff.go
  pkg/action/diff_local.go
  pkg/action/flags.go
  pkg/action/up.go
  pkg/helper/context.go
  pkg/helper/context_test.go
  pkg/helper/helm.go
  pkg/helper/helm_test.go
  pkg/hooks/run_test.go
  pkg/plan/build.go
  pkg/plan/build_charts_internal_test.go
  pkg/plan/build_manifests_internal_test.go
  pkg/plan/build_registries_internal_test.go
  pkg/plan/build_releases.go
  pkg/plan/build_releases_internal_test.go
  pkg/plan/build_repos_internal_test.go
  pkg/plan/build_values_internal_test.go
  pkg/plan/down_test.go
  pkg/plan/export_internal_test.go
  pkg/plan/import.go
  pkg/plan/kubedog_internal_test.go
  pkg/plan/list_test.go
  pkg/plan/mock_registry_export_test.go
  pkg/plan/mock_release_export_test.go
  pkg/plan/mock_repository_export_test.go
  pkg/plan/new_test.go
  pkg/plan/rollback_test.go
  pkg/plan/status_test.go
  pkg/plan/up_test.go
  pkg/plan/validate_test.go
  pkg/release/config.go
  pkg/release/config_test.go
  pkg/release/dependencies.go
  pkg/release/helm_actions.go
  pkg/release/uniqname/errors.go
  pkg/release/uniqname/uniqname.go
  pkg/release/uniqname/uniqname_test.go
  pkg/release/validate_test.go
  tests/01_helmwave.yml.tpl
Labels: size/M
